import re
from typing import List

from models.requirement import Requirement, SourceLocation


class SRSAgent:
    """
    Converts detected requirement candidates into the canonical Requirement
    representation used by the Retrieval Agent.
    """

    def __init__(self, llm_provider):
        self.llm_provider = llm_provider

    def extract(
        self,
        candidates: List[dict],
        progress_callback=None,
    ) -> List[Requirement]:
        """
        Send requirement candidates to the configured LLM provider and
        validate the structured response.
        """

        requirements = []
        source_ids = {
            self._candidate_requirement_id(candidate).casefold()
            for candidate in candidates
            if self._candidate_requirement_id(candidate)
        }
        used_ids = set()

        for index, candidate in enumerate(candidates, start=1):
            if progress_callback:
                progress_callback("requirement_start", {
                    "index": index,
                    "total": len(candidates),
                    "requirement_id": self._candidate_requirement_id(candidate) or f"REQ-{index:03d}",
                    "text": candidate["text"],
                })

            prompt_source = dict(candidate.get("source", {}))
            if candidate.get("source_requirement_id"):
                prompt_source["requirement_id"] = candidate["source_requirement_id"]
            prompt = self._build_prompt(
                candidate["text"],
                prompt_source,
                index,
                candidate.get("input_kind", "document"),
            )

            try:
                response = self.llm_provider.generate_structured(
                    prompt=prompt,
                    schema=Requirement
                )

                response = self._normalize_category(
                    response,
                    candidate["text"],
                    candidate.get("input_kind", "document"),
                    candidate.get("source_requirement_id"),
                )
                response = self._fill_obvious_fields(response, candidate["text"])
                requirement = Requirement.model_validate(response)
            except Exception as exc:
                if progress_callback:
                    progress_callback("requirement_error", {
                        "index": index,
                        "error": str(exc),
                    })
                raise
            # IDs, verbatim text, and provenance are controlled by the
            # application pipeline rather than generated by the language model.
            source_id = self._candidate_requirement_id(candidate)
            if source_id:
                requirement_id = source_id
                id_source = "source"
            else:
                generated_number = index
                requirement_id = f"REQ-{generated_number:03d}"
                while requirement_id.casefold() in source_ids or requirement_id.casefold() in used_ids:
                    generated_number += 1
                    requirement_id = f"REQ-{generated_number:03d}"
                id_source = "generated"
            used_ids.add(requirement_id.casefold())

            requirement = requirement.model_copy(update={
                "requirement_id": requirement_id,
                "id_source": id_source,
                "raw_text": candidate["text"],
                "source": SourceLocation.model_validate(candidate.get("source", {})),
            })
            requirements.append(requirement)

            if progress_callback:
                progress_callback("requirement_done", {
                    "index": index,
                    "total": len(candidates),
                    "requirement": requirement,
                })

        return requirements

    @staticmethod
    def _source_requirement_id(raw_text: str) -> str | None:
        """Read a leading requirement label such as FR-01.2 or NFR-03."""
        match = re.match(
            r"^\s*(?:[-*•]\s*)?\(?([A-Za-z][A-Za-z0-9_-]*[-_]\d+(?:[.-]\d+)*)\)?(?=\s|:|\.|\))",
            raw_text,
        )
        return match.group(1) if match else None

    @classmethod
    def _candidate_requirement_id(cls, candidate: dict) -> str | None:
        return candidate.get("source_requirement_id") or cls._source_requirement_id(candidate["text"])

    @classmethod
    def _normalize_category(
        cls,
        response: dict,
        raw_text: str,
        input_kind: str,
        source_requirement_id: str | None = None,
    ) -> dict:
        """Normalize legacy model labels into a base type plus specific subtype."""
        result = dict(response)
        old_type = str(result.get("type", "other")).strip().lower().replace("_", "-")
        subtype = str(result.get("subtype", "")).strip().lower()
        if subtype == "general":
            subtype = ""
        legacy_subtypes = {
            "interface": "interface",
            "data": "data management",
            "constraint": "constraint",
        }

        if old_type in legacy_subtypes and not subtype:
            subtype = legacy_subtypes[old_type]

        source_id = source_requirement_id or cls._source_requirement_id(raw_text)
        id_prefix = source_id.split("-", 1)[0].split("_", 1)[0].upper() if source_id else ""
        if id_prefix in {"F", "FR", "FREQ", "FUNC", "FUNCTIONAL"}:
            normalized_type = "functional"
        elif id_prefix in {"NF", "NFR", "NFRQ", "NONFUNC", "QUALITY"}:
            normalized_type = "non-functional"
        elif input_kind == "text":
            # Free-form text has no SRS classification context. Keep the
            # model's specific interpretation in subtype under the `other` base.
            if not subtype:
                subtype = old_type if old_type not in {"functional", "non-functional", "other"} else cls._infer_subtype(raw_text)
            normalized_type = "other"
        elif old_type in {"functional", "non-functional"}:
            normalized_type = old_type
        elif old_type == "other" and input_kind == "document":
            # SRS-document requirements must resolve to one of the two SRS
            # classes. If the model is unsure, infer from quality language and
            # use functional as the conservative default for behavior statements.
            normalized_type = cls._infer_document_type(raw_text, subtype)
        elif old_type == "other":
            normalized_type = "other"
        elif old_type in {"interface", "data"}:
            normalized_type = "functional"
        elif old_type == "constraint":
            normalized_type = "non-functional"
        else:
            normalized_type = "other"

        if not subtype:
            subtype = cls._infer_subtype(raw_text)

        result["type"] = normalized_type
        result["subtype"] = subtype or "general"
        return result

    @staticmethod
    def _infer_document_type(raw_text: str, subtype: str) -> str:
        text = f"{raw_text} {subtype}".lower()
        quality_terms = (
            "performance", "response time", "latency", "throughput", "scalability",
            "security", "secure", "authentication", "authorization", "availability",
            "reliability", "usability", "accessible", "maintainability", "compatibility",
            "portability", "privacy", "confidentiality", "resource constraint",
        )
        if any(term in text for term in quality_terms):
            return "non-functional"
        return "functional"

    @staticmethod
    def _infer_subtype(raw_text: str) -> str:
        text = raw_text.lower()
        categories = (
            ("security", ("password", "authentication", "authorization", "secure", "sensitive", "access control")),
            ("performance", ("response time", "within", "seconds", "latency", "load", "throughput", "responsive")),
            ("usability", ("readable", "navigation", "user-friendly", "feedback", "accessibility")),
            ("availability", ("available", "availability", "uptime", "recover")),
            ("compatibility", ("browser", "compatible", "http", "https", "platform")),
            ("data management", ("database", "record", "data", "storage", "schema")),
            ("interface", ("interface", "screen", "form", "display", "button")),
        )
        for category, terms in categories:
            if any(term in text for term in terms):
                return category
        return "general"

    @staticmethod
    def _fill_obvious_fields(response: dict, raw_text: str) -> dict:
        """Fill core omissions only when the source text gives direct evidence."""
        result = dict(response)
        text = raw_text.lower()

        actors = {
            "user": r"\busers?\b",
            "administrator": r"\badmins?\b|\badministrators?\b",
            "customer": r"\bcustomers?\b",
            "manager": r"\bmanagers?\b",
            "operator": r"\boperators?\b",
        }
        if not result.get("actor"):
            result["actor"] = [name for name, pattern in actors.items() if re.search(pattern, text)]
            if not result["actor"] and re.search(
                r"\bsystem\s+(?:shall|must|should|will)\b", text
            ):
                result["actor"] = ["system"]

        if not result.get("actions"):
            action_match = re.search(
                r"\b(?:shall|must|should|will|needs to|required to|is required to)\s+"
                r"(?:(?:allow|enable)\s+(?:the\s+)?(?:users?|admins?|administrators?|customers?)\s+to\s+)?"
                r"(?P<action>[^.;,]+)",
                raw_text,
                re.IGNORECASE,
            )
            if action_match:
                action = re.split(
                    r"\b(?:if|unless|when|before|after|while|so that)\b",
                    action_match.group("action"),
                    maxsplit=1,
                    flags=re.IGNORECASE,
                )[0]
                action = re.sub(r"\b(their|his|her|its|a|an|the)\b", " ", action, flags=re.IGNORECASE)
                action = " ".join(action.split()).strip(" .")
                if action:
                    result["actions"] = [action.lower()]

        if not result.get("entities"):
            entity_terms = (
                "password", "email", "account", "user", "profile",
                "order", "report", "payment", "request", "document", "file",
                "record", "session", "token", "notification",
            )
            result["entities"] = [
                term for term in entity_terms
                if re.search(rf"\b{re.escape(term)}s?\b", text)
            ]

        if not result.get("domain_terms") and result.get("entities"):
            terms = list(result["entities"])
            if "password" in terms:
                terms.extend(["password reset", "authentication"])
            if "email" in terms:
                terms.append("email notification")
            result["domain_terms"] = list(dict.fromkeys(terms))

        if not result.get("outputs") and "email" in text and re.search(
            r"\b(?:send|deliver|issue)\b", text
        ):
            result["outputs"] = ["confirmation email"]

        if not result.get("synonyms"):
            actions_text = " ".join(result.get("actions", [])).lower()
            if "reset" in actions_text and "password" in text:
                result["synonyms"] = ["reset password", "forgot password", "password recovery"]
            elif "email" in text and "send" in actions_text:
                result["synonyms"] = ["send confirmation email", "email confirmation", "reset notification"]

        if not str(result.get("title", "")).strip():
            normalized = str(result.get("normalized_text", "")).strip()
            result["title"] = normalized.rstrip(".").capitalize() if normalized else "Requirement"

        return result

    def _build_prompt(
        self,
        text: str,
        source: dict,
        index: int,
        input_kind: str,
    ) -> str:
        """Build the extraction prompt while preserving the original text."""

        return f"""
You are an SRS analysis agent.

Extract the software requirement from the provided text and return it
according to the supplied structured schema.

Rules:
- Preserve the requirement meaning.
- Do not invent implementation details.
- raw_text should exactly match the provided requirement text (the application will enforce this).
- Fill every field with useful information when it is stated or directly
  implied; use an empty list only when the requirement provides no evidence.
- title must be a short, specific name for the requirement (for example,
  "Password Reset" or "Reset Confirmation Email"). Do not return an empty title.
- Extract actors as the people or external systems performing/receiving actions
  (for example, ["user"]); actions as short verb phrases (for example,
  ["reset password"]); and entities as important domain nouns (for example,
  ["user", "password"]).
- Extract inputs and outputs, preconditions, postconditions, conditions,
  constraints, and error conditions when stated or directly implied.
- Decompose complex requirements into meaningful sub_requirements.
- Include useful domain_terms and synonyms for code retrieval when relevant.
- retrieval_text must be a concise space-separated set of key terms and actions.
- For a password reset requirement, useful fields could include actor ["user"],
  actions ["reset password"], entities ["user", "password"], title
  "Password Reset", and domain_terms ["password", "authentication"].
- If information is unavailable, use an empty list or appropriate empty value.
- requirement_id and id_source are assigned by the application.
- type must be exactly one of functional, non-functional, or other.
- subtype must be a concise specific classification, such as interface, security,
  performance, usability, data management, availability, or general.
- When input_kind is plain text, use type "other" and put the specific requirement
  classification in subtype. For SRS files, classify as functional or non-functional
  based on the requirement's purpose. An FR-prefixed ID means functional; an
  NFR-prefixed ID means non-functional.
- source should contain the provided source location.

Input kind: {input_kind}
Requirement:
{text}

Source:
{source}
"""
