import re
from typing import List

from models.requirement import Requirement, SourceLocation


class SRSAgent:
    """
    Converts detected requirement candidates into the canonical Requirement
    representation used by the Retrieval Agent.
    """

    def __init__(self, llm_provider):
        self.llm_provider = llm_provider

    def extract(
        self,
        candidates: List[dict],
        progress_callback=None,
    ) -> List[Requirement]:
        """
        Send requirement candidates to the configured LLM provider and
        validate the structured response.
        """

        requirements = []

        for index, candidate in enumerate(candidates, start=1):
            if progress_callback:
                progress_callback("requirement_start", {
                    "index": index,
                    "total": len(candidates),
                    "text": candidate["text"],
                })

            prompt = self._build_prompt(
                candidate["text"],
                candidate["source"],
                index
            )

            try:
                response = self.llm_provider.generate_structured(
                    prompt=prompt,
                    schema=Requirement
                )

                response = self._fill_obvious_fields(response, candidate["text"])
                requirement = Requirement.model_validate(response)
            except Exception as exc:
                if progress_callback:
                    progress_callback("requirement_error", {
                        "index": index,
                        "error": str(exc),
                    })
                raise
            # IDs, verbatim text, and provenance are controlled by the
            # application pipeline rather than generated by the language model.
            requirement = requirement.model_copy(update={
                "requirement_id": f"REQ-{index:03d}",
                "raw_text": candidate["text"],
                "source": SourceLocation.model_validate(candidate.get("source", {})),
            })
            requirements.append(requirement)

            if progress_callback:
                progress_callback("requirement_done", {
                    "index": index,
                    "total": len(candidates),
                    "requirement": requirement,
                })

        return requirements

    @staticmethod
    def _fill_obvious_fields(response: dict, raw_text: str) -> dict:
        """Fill core omissions only when the source text gives direct evidence."""
        result = dict(response)
        text = raw_text.lower()

        actors = {
            "user": r"\busers?\b",
            "administrator": r"\badmins?\b|\badministrators?\b",
            "customer": r"\bcustomers?\b",
            "manager": r"\bmanagers?\b",
            "operator": r"\boperators?\b",
        }
        if not result.get("actor"):
            result["actor"] = [name for name, pattern in actors.items() if re.search(pattern, text)]
            if not result["actor"] and re.search(
                r"\bsystem\s+(?:shall|must|should|will)\b", text
            ):
                result["actor"] = ["system"]

        if not result.get("actions"):
            action_match = re.search(
                r"\b(?:shall|must|should|will|needs to|required to|is required to)\s+"
                r"(?:(?:allow|enable)\s+(?:the\s+)?(?:users?|admins?|administrators?|customers?)\s+to\s+)?"
                r"(?P<action>[^.;,]+)",
                raw_text,
                re.IGNORECASE,
            )
            if action_match:
                action = re.split(
                    r"\b(?:if|unless|when|before|after|while|so that)\b",
                    action_match.group("action"),
                    maxsplit=1,
                    flags=re.IGNORECASE,
                )[0]
                action = re.sub(r"\b(their|his|her|its|a|an|the)\b", " ", action, flags=re.IGNORECASE)
                action = " ".join(action.split()).strip(" .")
                if action:
                    result["actions"] = [action.lower()]

        if not result.get("entities"):
            entity_terms = (
                "password", "email", "account", "user", "profile",
                "order", "report", "payment", "request", "document", "file",
                "record", "session", "token", "notification",
            )
            result["entities"] = [
                term for term in entity_terms
                if re.search(rf"\b{re.escape(term)}s?\b", text)
            ]

        if not result.get("domain_terms") and result.get("entities"):
            terms = list(result["entities"])
            if "password" in terms:
                terms.extend(["password reset", "authentication"])
            if "email" in terms:
                terms.append("email notification")
            result["domain_terms"] = list(dict.fromkeys(terms))

        if not result.get("outputs") and "email" in text and re.search(
            r"\b(?:send|deliver|issue)\b", text
        ):
            result["outputs"] = ["confirmation email"]

        if not result.get("synonyms"):
            actions_text = " ".join(result.get("actions", [])).lower()
            if "reset" in actions_text and "password" in text:
                result["synonyms"] = ["reset password", "forgot password", "password recovery"]
            elif "email" in text and "send" in actions_text:
                result["synonyms"] = ["send confirmation email", "email confirmation", "reset notification"]

        if not str(result.get("title", "")).strip():
            normalized = str(result.get("normalized_text", "")).strip()
            result["title"] = normalized.rstrip(".").capitalize() if normalized else "Requirement"

        return result

    def _build_prompt(
        self,
        text: str,
        source: dict,
        index: int
    ) -> str:
        """Build the extraction prompt while preserving the original text."""

        return f"""
You are an SRS analysis agent.

Extract the software requirement from the provided text and return it
according to the supplied structured schema.

Rules:
- Preserve the requirement meaning.
- Do not invent implementation details.
- raw_text should exactly match the provided requirement text (the application will enforce this).
- Fill every field with useful information when it is stated or directly
  implied; use an empty list only when the requirement provides no evidence.
- title must be a short, specific name for the requirement (for example,
  "Password Reset" or "Reset Confirmation Email"). Do not return an empty title.
- Extract actors as the people or external systems performing/receiving actions
  (for example, ["user"]); actions as short verb phrases (for example,
  ["reset password"]); and entities as important domain nouns (for example,
  ["user", "password"]).
- Extract inputs and outputs, preconditions, postconditions, conditions,
  constraints, and error conditions when stated or directly implied.
- Decompose complex requirements into meaningful sub_requirements.
- Include useful domain_terms and synonyms for code retrieval when relevant.
- retrieval_text must be a concise space-separated set of key terms and actions.
- For a password reset requirement, useful fields could include actor ["user"],
  actions ["reset password"], entities ["user", "password"], title
  "Password Reset", and domain_terms ["password", "authentication"].
- If information is unavailable, use an empty list or appropriate empty value.
- requirement_id is assigned by the application; use an empty string for requirement_id.
- type should be one of functional, non-functional, interface, data, constraint, or other.
- source should contain the provided source location.

Requirement:
{text}

Source:
{source}
"""
