from typing import List

from models.requirement import Requirement, SourceLocation


class SRSAgent:
    """
    Converts detected requirement candidates into the canonical Requirement
    representation used by the Retrieval Agent.
    """

    def __init__(self, llm_provider):
        self.llm_provider = llm_provider

    def extract(
        self,
        candidates: List[dict]
    ) -> List[Requirement]:
        """
        Send requirement candidates to the configured LLM provider and
        validate the structured response.
        """

        requirements = []

        for index, candidate in enumerate(candidates, start=1):
            prompt = self._build_prompt(
                candidate["text"],
                candidate["source"],
                index
            )

            response = self.llm_provider.generate_structured(
                prompt=prompt,
                schema=Requirement
            )

            requirement = Requirement.model_validate(response)
            # IDs, verbatim text, and provenance are controlled by the
            # application pipeline rather than generated by the language model.
            requirements.append(requirement.model_copy(update={
                "requirement_id": f"REQ-{index:03d}",
                "raw_text": candidate["text"],
                "source": SourceLocation.model_validate(candidate.get("source", {})),
            }))

        return requirements

    def _build_prompt(
        self,
        text: str,
        source: dict,
        index: int
    ) -> str:
        """Build the extraction prompt while preserving the original text."""

        return f"""
You are an SRS analysis agent.

Extract the software requirement from the provided text and return it
according to the supplied structured schema.

Rules:
- Preserve the requirement meaning.
- Do not invent implementation details.
- raw_text should exactly match the provided requirement text (the application will enforce this).
- Extract actors, actions, entities, inputs, outputs, conditions,
  constraints, and error conditions when explicitly implied.
- Decompose complex requirements into meaningful sub_requirements.
- Generate useful domain_terms and synonyms for code retrieval.
- retrieval_text should combine the important concepts needed to find
  related source-code components.
- If information is unavailable, use an empty list or appropriate empty value.
- requirement_id is assigned by the application; use an empty string for requirement_id.
- type should be one of functional, non-functional, interface, data, constraint, or other.
- source should contain the provided source location.

Requirement:
{text}

Source:
{source}
"""
